# -*- coding: utf-8 -*-
"""Our_Social_Media_Analysis_with_Neo4j.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HPhJyxiOTfdinzTHFL73qJgDGD8x3jCq

# Install
"""

!pip install -q py2neo

"""#import"""

from py2neo import Graph
from py2neo import Node
from py2neo import Relationship
import pandas as pd

"""# Established a Connection:"""

graph = Graph(
    "bolt://44.198.58.112:7687",
    user="neo4j",
    password="lime-rock-points"
    )

"""# Social Media Nodes:"""

Instagram = Node("Social_Media", title="Instagram", tagline="Capture and Share the World's Moments")
Facebook = Node("Social_Media",  title="Facebook", tagline="It's quick and easy")
WhatsApp = Node("Social_Media",  title="WhatsApp", tagline="Hey there, I am using WhatsApp")
SnapChat = Node("Social_Media", title="SnapChat", tagline="THe fastest way to share a moment")
Youtube = Node("Social_Media", title="Youtube", tagline="Broadcast Yourself")
X = Node("Social_Media", title="X", tagline="Here, your voice matters")
LinkedIn = Node("Social_Media", title="LinkedIn", tagline="Sum up your Professional brand")

"""#User Nodes:
**as social media is nothing without the Users:**
"""

Chandler = Node("Person", name="Chandler Bing", dob=1968, country="USA", sex="Male")
Rachel = Node("Person", name="Rachel Green", dob=1969, country="USA", sex="Female")
Joey = Node("Person", name="Joey Tribbiani", dob=1967, country="USA", sex="Male")
Ross = Node("Person", name="Ross Geller", dob=1967, country="USA", sex="Male")
Monica = Node("Person", name="Monica Geller", dob=1967, country="USA", sex="Female")
Phoebe = Node("Person", name="Phoebe Buffay", dob=1971, country="USA", sex="Female")

Abhijit = Node("Person", name="Abhijit Singh ", dob=1980, country="India", sex="Male")
ACP = Node("Person", name="ACP Pradyuman ", dob=1960, country="India", sex="Male")
Tarika = Node("Person", name="DR Tarika ", dob=1986, country="India", sex="Female")
Purvi = Node("Person", name="Purvi Sayed ", dob=1988, country="India", sex="Female")
Shreya = Node("Person", name="Shreya Chedda", dob=1985, country="India", sex="Female")
Salunkhe = Node("Person", name="Dr R.P. Salunkhe ", dob=1965, country="India", sex="Male")
Fredricks = Node("Person", name="Fredricks ", dob=1975, country="India", sex="Male")
Sachin = Node("Person", name="Inspector Sachin", dob=1987, country="India", sex="Male")
Nikhil = Node("Person", name="Inspector Nikhil ", dob=1990, country="India", sex="Male")

Om = Node("Person", name="Om Gadekar", dob=2003, country="India", sex="Male")
Tanishq = Node("Person", name="Tanishq Jawanjal", dob=2004, country="India", sex="Male")
Samir = Node("Person", name="Samir Kamble", dob=2002, country="India", sex="Male")
Anuja = Node("Person", name="Anuja Jagtap", dob=2003, country="India", sex="Female")
Khushi = Node("Person", name="Khushi Kunte", dob=2003, country="India", sex="Female")
Abhay = Node("Person", name="Abhau Jadhav", dob=2003, country="India", sex="Male")
Aniket = Node("Person", name="Aniket Chopde ", dob=2003, country="India", sex="Male")

"""# Storing Nodes in Graph:"""

graph.create(Instagram | Facebook | WhatsApp | SnapChat | Youtube | X | LinkedIn)

graph.create(Chandler | Rachel | Joey | Ross | Monica | Phoebe
             | Om | Tanishq | Samir | Anuja | Khushi | Abhay
             | Aniket | Abhijit | ACP | Tarika |Purvi | Shreya
             | Salunkhe | Fredricks | Sachin | Nikhil)

"""# Adding Relationship between Social Media Nodes & User Nodes that we've created."""

graph.create(Relationship(Joey, "Uses", SnapChat, joinedyear=2014, screentime=47, rating=3))
graph.create(Relationship(Ross, "Uses", LinkedIn, joinedyear=2010, screentime=64, rating=5))
graph.create(Relationship(Ross, "Uses", X, joinedyear=2013, screentime=60, rating=4.6))
graph.create(Relationship(Monica, "Uses", Facebook, joinedyear=2019, screentime=97, rating=4.5))
graph.create(Relationship(Phoebe, "Uses", Facebook, joinedyear=2018, screentime=20, rating=3))
graph.create(Relationship(Om, "Uses", Instagram, joinedyear=2016, screentime=69, rating=4.9))
graph.create(Relationship(Samir, "Uses", Facebook, joinedyear=2016, screentime=94, rating=1))
graph.create(Relationship(Samir, "Uses", LinkedIn, joinedyear=2022, screentime=34, rating=4.8))
graph.create(Relationship(Anuja, "Uses", Youtube, joinedyear=2018, screentime=104, rating=4.6))
graph.create(Relationship(Anuja, "Uses", X, joinedyear=2022, screentime=24, rating=1.8))
graph.create(Relationship(Anuja, "Uses", Instagram, joinedyear = 2020, screentime = 120, rating = 4.8))
graph.create(Relationship(Khushi, "Uses", Youtube, joinedyear=2019, screentime=14, rating=5))
graph.create(Relationship(Khushi, "Uses", SnapChat, joinedyear=2020, screentime=36, rating=3.8))
graph.create(Relationship(Khushi, "Uses", LinkedIn, joinedyear=2021, screentime=20, rating=4))
graph.create(Relationship(Chandler, "Uses", Facebook, joinedyear=2016, screentime=30, rating=2))
graph.create(Relationship(Chandler, "Uses", WhatsApp, joinedyear=2016, screentime=70, rating=3))
graph.create(Relationship(Chandler, "Uses", Instagram, joinedyear=2012, screentime=150, rating=4.9))
graph.create(Relationship(Rachel, "Uses", WhatsApp, joinedyear=2018, screentime=100, rating=4))

graph.create(Relationship(Phoebe, "Uses", WhatsApp, joinedyear=2010, screentime=25, rating=5))
graph.create(Relationship(Rachel, "Uses", WhatsApp, joinedyear=2011, screentime=10, rating=4))
graph.create(Relationship(Om, "Uses", WhatsApp, joinedyear=2015, screentime=15, rating=5))
graph.create(Relationship(Monica, "Uses", WhatsApp, joinedyear=2013, screentime=30, rating=4))
graph.create(Relationship(Samir, "Uses", WhatsApp, joinedyear=2014, screentime=35, rating=5))
graph.create(Relationship(Ross, "Uses", WhatsApp, joinedyear=2015, screentime=40, rating=4))
graph.create(Relationship(Anuja, "Uses", WhatsApp, joinedyear=2016, screentime=45, rating=5))
graph.create(Relationship(Khushi, "Uses", WhatsApp, joinedyear=2017, screentime=50, rating=4))
graph.create(Relationship(Joey, "Uses", WhatsApp, joinedyear=2018, screentime=55, rating=5))

graph.create(Relationship(Tanishq, "Uses", Instagram, joinedyear=2018, screentime=80, rating=5))
graph.create(Relationship(ACP, "Uses", X, joinedyear=2014, screentime=20, rating=3))
graph.create(Relationship(Tarika, "Uses", Instagram, joinedyear=2015, screentime=130, rating=4))
graph.create(Relationship(Purvi, "Uses", Instagram, joinedyear=2017, screentime=100, rating=4))
graph.create(Relationship(Shreya, "Uses", Instagram, joinedyear=2018, screentime=40, rating=4))
graph.create(Relationship(Om, "Uses", LinkedIn, joinedyear=2023, screentime=10, rating=3))
graph.create(Relationship(Fredricks, "Uses", Youtube, joinedyear=2013, screentime=30, rating=3))
graph.create(Relationship(Sachin, "Uses", Youtube, joinedyear=2010, screentime=40, rating=4))
graph.create(Relationship(Nikhil, "Uses", Instagram, joinedyear=2012, screentime=50, rating=5))

graph.create(Relationship(Rachel, "Uses", Facebook, joinedyear=2017, screentime=43, rating=2))
graph.create(Relationship(Aniket, "Uses", X, joinedyear=2022, screentime=84, rating=4))
graph.create(Relationship(Aniket, "Uses", LinkedIn, joinedyear=2024, screentime=134, rating=1))
graph.create(Relationship(Aniket, "Uses", Youtube, joinedyear=2017, screentime=64, rating=4.8))
graph.create(Relationship(Abhay, "Uses", X, joinedyear=2020, screentime=54, rating=2.9))
graph.create(Relationship(Abhay, "Uses", SnapChat, joinedyear=2015, screentime=76, rating=3.8))
graph.create(Relationship(Abhay, "Uses", WhatsApp, joinedyear=2019, screentime=87, rating=2.6))
graph.create(Relationship(Tanishq, "Uses", Facebook, joinedyear=2017, screentime=29, rating=4.9))
graph.create(Relationship(Tanishq, "Uses", SnapChat, joinedyear=2018, screentime=48, rating=2.8))
graph.create(Relationship(Om, "Uses",       X, joinedyear=2024, screentime=86, rating=1.6))

graph.create(Relationship(Salunkhe, "Uses", LinkedIn, joinedyear=2019, screentime=10, rating=3))
graph.create(Relationship(Abhijit, "Uses", Instagram, joinedyear=2018, screentime=80, rating=5))

"""# Billions of users uses Social Media but using Neo4j. It makes Data Analysis Simple.

# Now Neo4j Database is established. now time to Data Analysis & get Insights from it.

#Top 5 platforms with most users?
"""

query1 = """
MATCH (p:Person)-[]->(s:Social_Media)
RETURN s.title, count(*) as Users
order by Users desc
limit 5
"""

result1 = graph.run(query1)
print("Top 5 Social Media platfroms used by Users: ")
for d in result1:
  print(d)

"""#Which platform has the highest rating?"""

query2 = """
MATCH (p:Person)-[r]->(s:Social_Media)
RETURN s.title AS Title, AVG(r.rating) as Rating
ORDER BY Rating DESC
 """

result2 = graph.run(query2)
print("Which platform has the highest rating?")
for d in result2:
 print(d)

"""#What is the total screen time for a user & which social media platform has the most screen time?"""

query3="""
MATCH (p:Person)-[r]->(s:Social_Media)
return distinct p.name as Name, s.title, SUM(r.screentime) as Total
order by Total desc
limit 10
"""

result3 = graph.run(query3)

df = pd.DataFrame(result3,columns=["User","Social Media"," Screen Time"])

df

"""#Find the Eldest Person & the Youngest Person with their choice of Social Media"""

query4 = """
MATCH (p:Person)-[r]->(s:Social_Media)
SET p.Name = 'Eldest Person :'
RETURN p.Name, p.name AS Name, 2025-p.dob AS Age, s.title
ORDER BY Age DESC
LIMIT 1
UNION ALL
MATCH (p:Person)-[r]->(s:Social_Media)
SET p.Name = 'Youngest Person: '
RETURN p.Name ,p.name AS Name, 2025-p.dob AS Age, s.title
ORDER BY Age
LIMIT 1
"""

result4 = graph.run(query4)
for d in result4:
    print(d)

"""#Find the number of male & female users for each social media platform."""

query5 = """
MATCH (p:Person)-[r]->(s:Social_Media)
WHERE p.sex="Male"
SET p.surname = 'Male'
RETURN s.title, COUNT(*),p.surname AS count
ORDER BY count DESC
UNION ALL
MATCH (p:Person)-[r]->(s:Social_Media)
WHERE p.sex="Female"
SET p.surname = 'Female'
RETURN s.title, COUNT(*),p.surname AS count
ORDER BY count DESC
"""

result5 = graph.run(query5)
for d in result5:
    print(d)